#!/system/bin/sh
#
# Print startup info
#

L="log -p i -t halogenOS"
AL="log -p i -t aosp"

$AL "Welcome to Android `getprop ro.build.version.release` / The Android Open Source Project";

$L " ____________________________________ "
$L "|                                    |"
$L "|      Thanks a lot for choosing     |"
$L "|                                    |"
$L "| Y88b   d88P  .d88888b.   .d8888b.  |" 
$L "|  Y88b d88P  d88P' 'Y88b d88P  Y88b |" 
$L "|   Y88o88P   888     888 Y88b.      |"      
$L "|    Y888P    888     888  'Y888b.   |"   
$L "|    d888b    888     888     'Y88b. |" 
$L "|   d88888b   888     888       '888 |" 
$L "|  d88P Y88b  Y88b. .d88P Y88b  d88P |" 
$L "| d88P   Y88b  'Y88888P'   'Y8888P'  |"  
$L "|                                    |"
$L "|   We believe that you'll love it!  |"
$L "|____________________________________|"
