#!/system/bin/sh

if [ -f /data/xos/exitsafemode ]; then
  setprop persist.sys.safemode 0
  setprop persist.sw.safemode 0
  echo "0" > /data/property/persist.sys.safemode
  echo "0" > /data/property/persist.sw.safemode
  rm /data/xos/exitsafemode
fi

if [ -f /data/xos/safemode ]; then
  setprop persist.sys.safemode 1
  setprop persist.sw.safemode 1
  echo "1" > /data/property/persist.sys.safemode
  echo "1" > /data/property/persist.sw.safemode
  touch /data/xos/exitsafemode
  rm /data/xos/safemode
fi
